// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
   learnSidebar: [
    {
      type: 'link',
      label: 'Go To Store ', // 你想显示的链接文本
      href: 'https://www.toocaa.com', // 替换为你的链接地址
      className: 'custom-link',  // 应用自定义样式类
    },
    { type: 'autogenerated', dirName: '.' }, // 继续生成其他文档
  ],
};

module.exports = sidebars;
