// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
   learnSidebar: [
    {
      type: 'link',
      label: 'Go To Store ', 
      href: 'https://www.toocaa.com', 
      className: 'custom-link',  
    },
    { type: 'autogenerated', dirName: '.' }, 
  ],
};

module.exports = sidebars;
