name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yar
          
      - name: Adding known hosts
        run: ssh  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
