name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: placeholder

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy to https://www.wiki.toocaa.com/
        run: |
            echo "Destination path: ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} ${{ secrets.SERVER_PATH }}"

